### ISSUE TITLE
Auto-regeneration doesn't work

### ISSUE THREAD

**Issue by dozoruk** [envygeeks/jekyll-docker#210]
- [+] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [+] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [ ] I Am on macOS

## Description
 Auto-regeneration doesn't work, --incremental do nothing :/

here what I do:
`docker run --rm --label=jekyll --volume=//c/Repository/page:/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll serve --incremental `

**Comment by envygeeks** [comment]
This should be taken up with Jekyll, or with Docker, as this bug would rely on them to fix.  If Docker on Windows still uses a virtual machine, that would be why it doesn't work, especially if it still uses VirtualBox which has known file sync bugs because of complexities in the vfs.

Sorry I couldn't do more to help you!

**Comment by claudiuconstantin** [comment]
So auto generation cannot work via Docker container?
