### ISSUE TITLE
Wrong reference to embedded images

### ISSUE THREAD

**Issue by Agazoth** [envygeeks/jekyll-docker#219]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [x] I Am on Windows
  - [x] Docker for Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [ ] I Am on macOS

## Description

When running jekyll/jekyll on Docker for Windows as described below, links based on {{ site.url }} resolve to 0.0.0.0 and not 127.0.0.1 resulting in broken links to embedded images:
![image](https://bit.ly/2HEKhoM)

## Steps

```powershell
docker run --rm -v C:\`lab\MyLab\:/srv/jekyll -p 4000:4000 -it jekyll/jekyll jekyll serve
```
## Output

```powershell
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating...
                    done in 1.579 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

## Expected

```powershell
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating...
                    done in 1.579 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

## Test in Ubuntu for Windows

```ssh
jekyll serve
Configuration file: /mnt/c/lab/MyLab/_config.yml
            Source: /mnt/c/lab/MyLab
       Destination: /mnt/c/lab/MyLab/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.961 seconds.
                    Auto-regeneration may not work on some Windows versions.
                    Please see: https://github.com/Microsoft/BashOnWindows/issues/216
                    If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
 Auto-regeneration: enabled for '/mnt/c/lab/MyLab'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
``

**Comment by envygeeks** [comment]
Jekyll makes very bad defacto assumptions when they tightly coupled the binding host for the server to the url host they choose to use, and present to you. There is no way we can stop that problem other than to rewrite pieces of Jekyll (probably not gonna happen,) or to ask you to file a bug with Jekyll and point out that binding the bind host to the url host is error prone when ran behind a proxy.  Though, they're unlikely to fix the issue, since it's existed since about 3.3 AFAIW.

We need the server to be bound to 0.0.0.0 to forward it to your system, and they tightly couple logic that shouldn't be coupled together in a way that presents as a bug from us, but it's really not, because we can't do anything to fix it (sadly.)

There are two ways you can fix it quickly yourself:

1. Drop `{{ site.url }}` and use absolute URL's without protocol
1. Do 1 and use `{% if jekyll.env == "production" %}<base href={{ site.url }}>{% endif %}`
1. Use `{{ site.baseurl }}`
