### ISSUE TITLE
HEAD commit on master was forcefully changed

### ISSUE THREAD

**Issue by SISheogorath** [envygeeks/jekyll-docker#270]
I just noticed that yesterday the latest commit 0789bc1a4529a72caceb193f5272e51987cdf2f1 was changed by a force push. Previously I was this commit: https://github.com/envygeeks/jekyll-docker/commit/d567ca8e579ba0798a1a1137f3aab0fd06a75fb6

Was there a specific reason to do that? Especially before the original one was signed and the new one isn't. And why after such a long time?

I want to mention that this is probably not a security issue, because the remaining history stayed intact and also the content of the commit was not changed, except of the missing signature.

**Comment by envygeeks** [comment]
It was intentionally done by me, so indeed there is no security issue, as far as why, it was done because Github made a mistake with the way it handled the by line and I just noticed when somebody contacted me to fix a problem with this repo. 

As far as being signed, that is non-relevant to me because it is *not my signature* that was used to verify that commit, but Github's, and I do not control that key so I do not necessarily trust it to verify that I am me because they literally do not verification before making and signing the commit from their website (I don't fully understand why they chose to do website based signatures the way they did anyways, it's just theater IMO.)

**Comment by SISheogorath** [comment]
I have indeed not checked if it was your signature on the previous one, which explains why it's gone. All good then, thanks for the quick response!

**Comment by envygeeks** [comment]
I should finally upgrade my ubikey so I can use it with my new MBP now that somebody brought it up.
